### ISSUE TITLE
Build errors on 2018.3

### ISSUE THREAD

**Issue by david-pfx** [dgkanatsios/MatchThreeGame#1]
Web Player no longer supported.
Various warnings.

**Comment by dgkanatsios** [comment]
thanks, have you tried to use a newer version to see if these warnings have disappeared?
In any case, feel free to create a Pull Request that fixes these issues.

**Comment by david-pfx** [comment]
I think you just need to load your project into a new version of Unity, fix the warnings and push the changes. Quicker than a PR, I think.

**Comment by BigHandInSky** [comment]
Error is in GoSpline line 62, replacing:
```
if( Application.platform == RuntimePlatform.OSXWebPlayer || Application.platform == RuntimePlatform.WindowsWebPlayer )
```
with
```
if( Application.platform == RuntimePlatform.WebGLPlayer )
```
Should address it I think.

**Comment by dgkanatsios** [comment]
Project is running now
